# -*- coding: utf-8 -*-
"""Patterns.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kqx8fJtilo9BWsTN3jftgKYhYRh970g9
"""

matrix = []

for i in range(4):
  matrix.append([0]*4)

print(matrix)

rows = 4
cols = 4
i=0
j=0
count=1
while rows >0 and cols >0 :
  #Move right
  moves=0
  while(moves<cols):
    matrix[i][j]=count
    moves +=1
    j +=1
    count +=1
  rows -=1 #As one row is done now
  i +=1
  j -=1
  print(matrix)
  print("#######")
  #move down
  moves=0
  while(moves<rows):
    matrix[i][j]=count
    moves +=1
    i +=1
    count +=1
  #As one column is done more
  cols -=1
  j -=1
  i -=1
  print(matrix)
  print("#######")
  #move left
  moves=0
  while(moves<cols):
    matrix[i][j]=count
    moves +=1
    j -=1
    count +=1
  rows -=1 #As one row is done now
  i -=1
  j +=1
  print(matrix)
  print("#######")
  #move up
  moves=0
  while(moves<rows):
    matrix[i][j]=count
    moves +=1
    i -=1
    count +=1
  #As one column is done more
  cols -=1
  j +=1
  i +=1
  print(matrix)
  print("#######")

print(matrix)

'''
*       *
* *   * *
* * * * *
* * * * *
* * * * *

'''

for i in range(5):
  for j in range(5):
    if j<=i or j>=5-i-1 :
      print("*", end=" ")
    else:
      print(" ",end=" ")
  print()



'''
*           *
* *       * *
* * *   * * *
* * * * * * *
* * *   * * *
* *       * *
*           *
'''



n=7
for i in range(int(n/2)):
  for j in range(n):
    if j<=i or j>=n-i-1 :
      print("*", end=" ")
    else:
      print(" ",end=" ")
  print()

count = int(n/2)
while(count>=0):
    for j in range(n):
      if j<=count or j>=n-count-1 :
        print("*", end=" ")
      else :
        print(" ",end=" ")
    print()
    count -=1

'''
\******/
*\****/*
**\**/**
***\/***
***/\***
**/**\**
*/****\*
/******\

'''
n=7
for i in range(n):
  for j in range(n):
    if(j==i or i+j == n-1):
     if i+j == (n-1):
        print('/', end = '')
     else:
        print('\\', end = '')
    else:
        print('*', end = '')
  print()